name: Bug Report
description: Report a bug or issue in Athloop
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug in Athloop!

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (blocks users)
        - High (degrades UX)
        - Medium (annoying but workarounds exist)
        - Low (console noise, no user impact)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Where is the bug?
      options:
        - Backend
        - Frontend (iOS)
        - Both
        - Documentation
        - Infrastructure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What's the bug? What's happening vs what should happen?
      placeholder: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what's actually happening
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where did this happen?
      placeholder: |
        - iOS version:
        - App version:
        - Device:
        - Backend environment (local/production):
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: Any relevant logs, error messages, or screenshots
      placeholder: Paste logs or attach screenshots
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: User Impact
      description: How does this affect users?
      placeholder: Describe the impact on user experience
    validations:
      required: false

  - type: textarea
    id: related
    attributes:
      label: Related Issues/PRs
      description: Link to related issues or pull requests
      placeholder: "#123, #456"
    validations:
      required: false
