name: Feature Request
description: Propose a new feature for Athloop
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for Athloop!

  - type: dropdown
    id: version
    attributes:
      label: Target Version
      description: Which version should this feature be in?
      options:
        - v1.2
        - v1.3
        - v1.4
        - v1.5
        - v2.0
        - Future
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the app does this affect?
      options:
        - Backend
        - Frontend (iOS)
        - Both
        - Documentation
        - Infrastructure
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature from a user's perspective
      placeholder: |
        As a [persona/user type]
        I want [feature/capability]
        So that [benefit/value]
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context & Problem
      description: What problem does this solve? Why is it needed?
      placeholder: Explain the context and the problem this feature addresses
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Implementation Notes
      description: Any technical details, API changes, database migrations, etc.
      placeholder: Technical approach, dependencies, concerns
    validations:
      required: false

  - type: textarea
    id: testing
    attributes:
      label: Testing Requirements
      description: How should this be tested?
      placeholder: |
        - [ ] Unit tests
        - [ ] E2E tests
        - [ ] Manual testing scenarios
    validations:
      required: false

  - type: textarea
    id: related
    attributes:
      label: Related Issues/PRs
      description: Link to related issues or pull requests
      placeholder: "#123, #456"
    validations:
      required: false
